#pragma once

#include<thread>

#define CACHE_LINE_SIZE 128
#define L2_CACHE_SIZE 262144
#define PARTITION_SIZE (L2_CACHE_SIZE >> 3)

#define HASH_THRESHOLD 4

#define DBCONTEST_PAGE_SIZE 4096
#define DBCONTEST_PAGE_ITEM_COUNT (DBCONTEST_PAGE_SIZE >> 3)

#define DBCONTEST_PAGE_ALIGN(LEN)   \
    (((uint64_t) (LEN) + ((DBCONTEST_PAGE_SIZE) - 1)) & ~((uint64_t) ((DBCONTEST_PAGE_SIZE) - 1)))

#define DBCONTEST_ITEM_COUNT_ALIGN(CNT)   \
    (((uint64_t) (CNT) + ((DBCONTEST_PAGE_ITEM_COUNT) - 1)) & ~((uint64_t) ((DBCONTEST_PAGE_ITEM_COUNT) - 1)))

// sample max 1MB for each column
#define MAX_SAMPLE_SIZE 1048576UL

#define MAX_SAMPLE_ITEM_COUNT (MAX_SAMPLE_SIZE >> 3)

#define MAX_SAMPLE_COUNT 32768

// minimal scan size 4MB
#define MIN_SCAN_SIZE 4194304UL
#define MIN_SCAN_ITEM_COUNT (MIN_SCAN_SIZE >> 3)

#define MAX_TASK_CNT 40U
#define MIN_PARTITION_TABLE_SIZE 102400

#define MIN_PROBE_ITEM_CNT 1024
#define MAX_PROBE_TASK_CNT 16U

#define MIN_BUILD_ITEM_CNT 102400
#define MAX_BUILD_TASK_CNT 4U

#define MIN_FILTER_ITEM_CNT 1024
#define MAX_FILTER_TAKS_CNT 16U

#define USE_ASYNC_JOIN 1

#define USE_PARALLEL_QUERY 0

#define USE_PARALLEL_BUILD_HASH_TABLE 1

#define PRINT_LOG 0
